{{
    config(
        materialized='table'
    )
}}

SELECT 
    A.TRANSFORMATIONGROUP,
    A.SOURCETABLE, 
    A.SOURCETABLEPK, 
    B.SOURCECOLUMN,
    B.DEFAULTVALUE,
    B.TRANFORMATIONRULE,
    A.FILTERRULE,
    A.SOURCEFIELD,
    A.SOURCEFIELDVALUE,
    B.DESTINATIONTABLE,
    REPLACE(B.DESTINATIONCOLUMN,B.DESTINATIONTABLE) AS DESTINATIONCOLUMN,
    B.DESTINATIONDATATYPE,
    B.DESTINATIONISNULLABLE
FROM RAW.IC_REF.mapping_source_table A 
JOIN RAW.IC_REF.mapping_column B
    ON A.SOURCETABLE = B.SOURCETABLE
    AND A.TRANSFORMATIONGROUP = B.TRANSFORMATIONGROUP
WHERE A.SOURCETABLE = 'ADMINISTRATIONS'

